[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["Galen Elias <gelias@gmail.com>"]

[dependencies]
clap = "*"
regex = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
chrono = "*"
itertools = "*"
permutohedron = "*"
num = "0.2"


[[bin]]
name = "aoc"
path = "src/main.rs"